[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Routes admin et API vers les fonctions SSR (en premier !)
[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[redirects]]
  from = "/api/*" 
  to = "/.netlify/functions/entry"
  status = 200
  force = true

# Catch-all pour tout le reste vers la fonction SSR
# (Astro SSR gère automatiquement statique vs dynamique)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200
