import { c as createAstro, a as createComponent, f as renderHead, g as renderSlot, r as renderTemplate } from './astro/server_pONdjIwT.mjs';
import 'kleur/colors';
import 'clsx';
/* empty css                          */

const $$Astro = createAstro("https://titusconsulting.be");
const $$AdminLayout = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$AdminLayout;
  const { title } = Astro2.props;
  return renderTemplate`<html lang="en" data-astro-cid-2kanml4j> <head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${title} | TestBot Chronicles Admin</title><link rel="icon" type="image/png" href="/favicon.png"><!-- Include a markdown editor library --><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde@2.18.0/dist/easymde.min.css">${renderHead()}</head> <body class="min-h-screen bg-gray-50" data-astro-cid-2kanml4j> <!-- Admin Header --> <header class="bg-slate-900 border-b border-gray-200 sticky top-0 z-50" data-astro-cid-2kanml4j> <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8" data-astro-cid-2kanml4j> <div class="flex justify-between h-16" data-astro-cid-2kanml4j> <div class="flex items-center" data-astro-cid-2kanml4j> <a href="/admin" class="flex items-center space-x-3" data-astro-cid-2kanml4j> <img src="/images/brand/titusLogo.png" alt="TestBot Chronicles" class="h-8 w-auto" data-astro-cid-2kanml4j> <span class="text-xl font-bold text-white" data-astro-cid-2kanml4j>TestBot Admin</span> </a> </div> <div class="flex items-center space-x-6" data-astro-cid-2kanml4j> <a href="/admin" class="text-gray-300 hover:text-white transition font-medium" data-astro-cid-2kanml4j>Dashboard</a> <a href="/admin/new-post" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition font-medium" data-astro-cid-2kanml4j>New Post</a> <a href="/" class="text-gray-300 hover:text-white transition font-medium" data-astro-cid-2kanml4j>View Site</a> <button id="logout-btn" class="text-gray-300 hover:text-white transition font-medium border border-gray-600 px-3 py-1 rounded" data-astro-cid-2kanml4j> <svg id="logout-icon" class="w-4 h-4 inline mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" data-astro-cid-2kanml4j> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" data-astro-cid-2kanml4j></path> </svg> <svg id="logout-loading" class="w-4 h-4 inline mr-1 animate-spin hidden" fill="none" viewBox="0 0 24 24" data-astro-cid-2kanml4j> <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" data-astro-cid-2kanml4j></circle> <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" data-astro-cid-2kanml4j></path> </svg> <span id="logout-text" data-astro-cid-2kanml4j>Logout</span> </button> </div> </div> </div> </header> <!-- Admin Content --> <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8" data-astro-cid-2kanml4j> ${renderSlot($$result, $$slots["default"])} </main>  </body> </html> `;
}, "C:/Users/qgoos/Desktop/TestBot-Chronicles/testbot-chronicles/src/layouts/AdminLayout.astro", void 0);

export { $$AdminLayout as $ };
